### ISSUE TITLE
Clean-up repository files

### ISSUE THREAD

**Issue by wbigger** [Born2Code-2017/CircoloLetterario#1]
The repository has a lot of folders and it is unclear the purpose of many of them. A clean-up is recommended.

- [ ] remove personal named folder (e.g. LucaSite or homeGabry); the master branch should include only the "official", shared version of the project. Use local branches to experiment or feature/issue branch for work-in-progress.
- [ ] add a README.md that explains the contents of the folders.
- [ ] remove unused/useless files, if any
- [ ] if you have any .zip or similar compressed file that represents a specific snapshot of the project that you consider important, add it as 'Release' on GitHub.

**Comment by lucaleone** [comment]
with the 'issue: Clean-up repository files' commit the project:
-has been cleaned
.readme.md added
-zip removed
