### ISSUE TITLE
US13: DETTAGLIO EVENTI

### ISSUE THREAD

**Issue by AlessiaAngelone** [Born2Code-2017/CircoloLetterario#17]
Titolo: Come utente, voglio cliccare su un evento e visualizzare le informazioni di dettaglio.

Dimostrazione: : dopo l’autenticazione iniziale, l’utente accede a http://localhost:4200/home e visualizza gli eventi a cui parteciperà secondo un ordine cronologico. Cliccando sulla “card” relativa all’evento, il contenitore dell’evento si espande e verranno visualizzati i dettagli come da wireframe 

Punti: 4

Owner: --

**Comment by lucaleone** [comment]
lo style è stato cambiato, ora gli eventi visualizzano tutte le info necessarie.
