### ISSUE TITLE
US14: interfaccia homepage

### ISSUE THREAD

**Issue by AlessiaAngelone** [Born2Code-2017/CircoloLetterario#18]
Titolo: Come gestore, voglio avere l’interfaccia della homepage più facile e intuitiva per rendere l’utilizzo piu semplice.

Dimostrazione: quando l’utente accede l’utente accede a HOME http://localhost:4200/ visualizza gli eventi a cui parteciperà secondo un ordine cronologico. Ogni evento verrà visualizzato sotto forma di “card”. Sugli eventi verranno visualizzati dei pulsanti:
 	“modifica” (per modificare l’evento solo se owner) ,
“cancella” (per cancellare l’evento solo se owner),
“segnalibro” (per segnalare la partecipazione all’evento).
Sul lato destro della pagina saranno presenti due pulsanti, uno per aprire il calendario dedicato al filtraggio degli eventi per data, uno per aggiungere un nuovo evento. 
Nell’intestazione della pagina sarà presente in ogni sezione dell’applicazione e contiene: 
“hamburger-button” (per la navigazione tra le varie sezioni dell’applicazione),
“logo” (per tornare alla home da qualsiasi sezione),
“notifiche” (per segnalare la presenza di nuovi eventi – non ancora implementata). 

Punti: 4 

Owner: grafica e menu laterale: Luca; gestione eventi Gabriele

**Comment by AlessiaAngelone** [comment]
@lucaleone è questo quello che avevi in mente?

**Comment by lucaleone** [comment]
solo un'aggiunta alla descrizione: in oltre le card hanno il pulsante per rimuovere la partecicazione

**Comment by lucaleone** [comment]
funzionalità implementate come da descrizione
