### ISSUE TITLE
Cannot set a time field in new event

### ISSUE THREAD

**Issue by wbigger** [Born2Code-2017/CircoloLetterario#3]
The time field in the new event form has three subfield. I can set the first two (see image), but not the third.

By the way, which is the meaning of that field?

<img width="173" alt="screen shot 2017-11-29 at 9 49 21 am" src="https://user-images.githubusercontent.com/3594326/33366221-db1da432-d4ea-11e7-8b51-1eb90a86ee10.png">

**Comment by lucaleone** [comment]
step="60" added to the input tag
Issue fix to be tested. In chrome 62.0.3202.94 the 'seconds' field doesn't appear. which browser did you use?

**Comment by wbigger** [comment]
It was a problem with my locale, set to en-US. Those last two dashes was for AM/PM. If I set local to it-IT, it give me the 24h format, more familiar to me.
