### ISSUE TITLE
US1: creazione di un nuovo evento

### ISSUE THREAD

**Issue by AlessiaAngelone** [Born2Code-2017/CircoloLetterario#4]
Titolo: come utente, voglio creare un nuovo evento per condividere interessi.

Dimostrazione: accedo a localhost:4200/new-event visualizzo il form per la compilazione o uno stub. Cliccando su 'invia' creo l'evento sul database remoto e visualizzo un popup di successo e torno nella home.  

Punti: 4

Owner: Alessia

**Comment by AlessiaAngelone** [comment]
Bisogna impostare l'owner dell'evento con il nome dell'utente loggato

**Comment by lucaleone** [comment]
Grafica aggiunta, funzionalità aggiunte in gruppo
