### ISSUE TITLE
US5: modificare eventi

### ISSUE THREAD

**Issue by AlessiaAngelone** [Born2Code-2017/CircoloLetterario#8]
Titolo: come utente, voglio modificare un evento da me organizzato per correggere errori.

Dimostrazione: dopo l’autenticazione iniziale, l’utente accede a localhost:4200/home e visualizza gli eventi a cui parteciperà secondo un ordine cronologico. Cliccando sul pulsante “modifica” presente sull’evento desiderato, compare un form con i dati da modificare. Una volta apportate le modifiche desiderate, cliccando su 'invia' l'evento viene modificato sul database remoto, verrà visualizzato un popup di successo e l’utente torna alla home. Invece cliccando su 'cancella'  le modifiche apportate non verranno considerate e l’utente torna alla home.

Punti: 8

**Comment by lucaleone** [comment]
Grafica in home aggiunta
Funzionalità implementata da @gabrielepiaggesi è @AlessiaAngelone
