### ISSUE TITLE
US6: eliminare eventi

### ISSUE THREAD

**Issue by AlessiaAngelone** [Born2Code-2017/CircoloLetterario#9]
Titolo: come utente, voglio eliminare un evento da me organizzato dalla lista per imprevisti.

Dimostrazione: dopo l’autenticazione iniziale, l’utente accede a localhost:4200/home e visualizza gli eventi a cui parteciperà secondo un ordine cronologico. Cliccando sul pulsante “elimina” presente sull’evento desiderato, compare un alert per confermare o annullare l’eliminazione di quell’evento. Se confermo, l’evento viene eliminato dalla lista.

Punti: 4

Owner: Gabriele

**Comment by lucaleone** [comment]
Grafica intuitiva per pulsante cancella aggiunta
Funzionalità aggiunta da @gabrielepiaggesi , confermi?

**Comment by gabrielepiaggesi** [comment]
confermo, funziona
